---
title: Ideals on the shelf
author: Joe Powers
date: '2018-06-28'
slug: ideals-on-the-shelf
categories: []
tags: []
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
---

For many years I was in love with a friend, but we were never single at the same time, so it never happened. Until it did, she got out of a relationship in 2007 and I jumped out of a three-years relationship for what I thought might be my last chance. People were starting to get married by then after all. 

The relatinoship did not go well. It was entirely my own fault. In years of longing I had built up a person and an idea of a relationship with that person that did not match reality. We ended it after 6 months and amazingly have salvaged and fully restored the friendship that preceeded our brief attempt at romance.

What happened next made the whole misadventure worthwhile. I started taking seriously the women I did have access to. I was completely serious in the relationships that followed. I had no Holy Grail that would allow me to overlook my current relationship as short term, or of course it was inadequate the perfect woman is waiting on the shelf. 
I started to grow a lot as a person. 
Now I face a similar dilemma with work and its relevance. I still have an idela on the shelf of being a DS at a political campaign or charter school. And I overloook the smaller ops for imapct because the big one is out there waiting for me. 