---
title: Expert Novices
author: Joe Powers
date: '2018-06-25'
slug: expert-novices
categories: []
tags: []
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
---

[use rock rolling god pic: Sisiphus]

Experts spend more time planning than novices, who tend to jump right in and start doing. The implication is that novices should try to plan the way experts do. There is a problem with this advice: Novices (by definition) don't know what to anticipate and thus cannot plan. You need experience in order to plan, so to become an expert, novices should start racking up experience. Jump in. 

What about teh role of novices who model expert behavior? This is promising, but keep in mind also how experts are still mindlessly mimicking the nuances of their masters. The repetition of these empty nuances is probably still more efficient than learning from scratch, however. 

I stumble over this problem with planning for data munging and EDA. How far should I plan ahead. It's EDA. Great to have "all the data" ready and clean, but in this age, that is literally an endless task. So make your best plan (which will be limited by your ignorance), talk to a more expert person if one or more are available, and then just start. You will have to back track, but this is where the `makefile` comes in. 

For iterative data munging I have found no other technique that comes close. 

A few tips: 

Store your paths in a central doc, but load all files at teh top of the script. This ensures you can check your make file easily. 

Make your best guess at a an output and how you might get there. But the ratio of unknown to known is so high that you are better off just getting started than plannig to a tee. 
