---
title: web scraping with R
author: Joe Powers
date: '2018-07-10'
slug: web-scraping-with-r
categories: []
tags: []
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
---

Using [Jason Goodman's post](https://medium.com/@jasonkgoodman/advice-on-building-data-portfolio-projects-c5f96d8a0627) as a launch pad I started scarping data. 

```{r}
library(rvest)
```

```{r}
school_ranks_url <- "https://www.nerdwallet.com/blog/mortgages/best-school-districts-southern-california-2015/"

wp_ranks <- read_html(school_ranks_url)

ranks_raw <- html_nodes(wp_ranks, "td") %>% html_text()

class(ranks_raw)

matrix(ranks_raw, ncol = 9, nrow = 153) %>% 
  data.frame()
```

Another option is the [rvest](https://www.analyticsvidhya.com/blog/2017/03/beginners-guide-on-web-scraping-in-r-using-rvest-with-hands-on-knowledge/) package. 

It will help if you install the [selector gadget](https://selectorgadget.com/), a Chrome-approved browser extension. 

```{r}
#Loading the rvest package
library(rvest)

#Specifying the url for desired website to be scrapped
imdb_url <- "http://www.imdb.com/search/title?count=100&release_date=2016,2016&title_type=feature"

#Reading the HTML code from the website
webpage <- read_html(imdb_url)
```

```{r}
#Using CSS selectors to scrap the rankings section
rank_data_html <- html_nodes(webpage, '.text-primary')

#Converting the ranking data to text
rank_data <- html_text(rank_data_html)

#Let's have a look at the rankings
head(rank_data)

#Data-Preprocessing: Converting rankings to numerical
rank_data <- as.numeric(rank_data)
```

