---
title: Map2
author: Joe Powers
date: '2018-07-10'
slug: map2
categories: []
tags: []
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
---

Note that `map2()` seems to requires vector arguments in the form `df$var`
```{r reprex, eval=FALSE}
library(dplyr)
library(purrr)

# Create frequency table
ds_cyl_n <- mtcars %>% count(cyl)
	
# Create custom function for use in map()
my_sample_n <- function(x, y){
	
	mtcars %>% 
		filter(cyl == x) %>% 
		sample_n( 
			size = y, 
			replace = TRUE
		) 
}
	
# hacky map
map2_df(.x = ds_cyl_n$cyl, .y = ds_cyl_n$n, .f = my_sample_n)
```

`pmap()` should be able to handle the dataframe as an argument but only when the column names are the same as the argument names expected by the function. 
```{r reprex, eval=FALSE}
# Create frequency table
ds_cyl_n <- 
  mtcars %>% 
  count(cyl) %>% 
  rename(cyl_n = cyl, size = n)
	
# Create custom function for use in map()
my_sample_n <- function(cyl_n){
	
	mtcars %>% 
		filter(cyl == cyl_n) %>% # struggling here to filter based on argument in df
		sample_n(replace = TRUE) 
}
	
# hacky map
pmap(ds_cyl_n, my_sample_n)
```

```{r reprex fails, eval=FALSE}
library(dplyr)
library(purrr)

# Create frequency table
ds_cyl_n <- mtcars %>% count(cyl)
	
# Create custom function for use in map()
my_sample_n <- function(x, y){
	x <- enquo(x)
	y <- enquo(y)
	
	mtcars %>% 
		filter(cyl == !!x) %>% 
		sample_n( 
			size = !!y, 
			replace = TRUE
		) 
}
	
# hacky map
map2(.x = ds_cyl_n$cyl, .y = ds_cyl_n$n, .f = my_sample_n)
```



